Repository tak-st/Saifu-Android, pull requests merged in 2020-08, with the labels that each got.

#50 欲しい物リストの項目編集機能を実装した。
  app/src/main/java/com/ze20/saifu/AddWishActivity.kt
  app/src/main/java/com/ze20/saifu/ui/wish/WishFragment.kt
  app/src/main/res/drawable/custom_button_danger.xml
  app/src/main/res/drawable/ic_baseline_delete_24.xml
  app/src/main/res/drawable/ic_baseline_share_24.xml
  app/src/main/res/drawable/ic_edit_24dp.xml
  app/src/main/res/layout/activity_add_wish.xml
  app/src/main/res/layout/fragment_wish_list.xml
  app/src/main/res/values/strings.xml
Labels: 機能強化

#52 バッジをたくさんつけた
  README.md
Labels: 機能強化

#53 add GPL License
  LICENSE
Labels: ドキュメンテーション

#54 ログ一覧表示しました。
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment1.kt
  app/src/main/java/com/ze20/saifu/ui/log/logFragment.kt
  app/src/main/res/drawable/horizon_line.xml
  app/src/main/res/layout/fragment_log.xml
  app/src/main/res/layout/fragment_log_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 機能強化

#55 readmeに画像入れたりした
  README.md
Labels: レビュー待ち, 機能強化

#56 欲しい物リストからデータ入力画面にデータを渡せるように
  app/src/main/java/com/ze20/saifu/DataInputActivity.kt
  app/src/main/java/com/ze20/saifu/ui/wish/WishFragment.kt
  app/src/main/res/layout/activity_add_wish.xml
  app/src/main/res/layout/activity_data_input.xml
Labels: レビュー待ち, 機能強化

#57 画面推移の作成
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ze20/saifu/GraphActivity.kt
  app/src/main/java/com/ze20/saifu/ui/budget/BudgetActivity.kt
  app/src/main/java/com/ze20/saifu/ui/home/HomeFragment.kt
  app/src/main/java/com/ze20/saifu/ui/log/logFragment.kt
  app/src/main/java/com/ze20/saifu/ui/setting/SettingsFragment.kt
  app/src/main/res/layout/activity_graph.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/search_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/root_preferences.xml
Labels: レビュー待ち, 機能強化

#58 ショートカットボタン周りの機能を作成
  .idea/codeStyles/Project.xml
  app/src/main/java/com/ze20/saifu/AddWishActivity.kt
  app/src/main/java/com/ze20/saifu/ConvenientFunction.kt
  app/src/main/java/com/ze20/saifu/DataInputActivity.kt
  app/src/main/java/com/ze20/saifu/SQLiteDB.kt
  app/src/main/java/com/ze20/saifu/ui/home/HomeFragment.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment1.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment2.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment3.kt
  app/src/main/res/drawable/ic_baseline_double_arrow_48.xml
  app/src/main/res/drawable/ic_baseline_edit_128.xml
  app/src/main/res/drawable/ic_baseline_edit_48.xml
  app/src/main/res/layout/activity_sub_fragment1.xml
  app/src/main/res/layout/activity_sub_fragment2.xml
  app/src/main/res/layout/activity_sub_fragment3.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/root_preferences.xml
Labels: レビュー待ち, 機能強化

#59 データ入力画面と欲しい物追加画面の細かい手直し
  app/src/main/java/com/ze20/saifu/AddWishActivity.kt
  app/src/main/java/com/ze20/saifu/ConvenientFunction.kt
  app/src/main/java/com/ze20/saifu/DataInputActivity.kt
  app/src/main/res/values/strings.xml
Labels: バグ, リファクタリング

#61 いろんなファイルをフォルダ分けした
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ze20/saifu/ui/MainActivity.kt
  app/src/main/java/com/ze20/saifu/ui/calendar/CalendarActivity.kt
  app/src/main/java/com/ze20/saifu/ui/calendar/CalendarAdapter.kt
  app/src/main/java/com/ze20/saifu/ui/calendar/DateManager.kt
  app/src/main/java/com/ze20/saifu/ui/home/HomeFragment.kt
  app/src/main/java/com/ze20/saifu/ui/home/NotificationActivity.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment1.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment2.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment3.kt
  app/src/main/java/com/ze20/saifu/ui/input/DataInputActivity.kt
  app/src/main/java/com/ze20/saifu/ui/log/GraphActivity.kt
  app/src/main/java/com/ze20/saifu/ui/log/ReportActivity.kt
  app/src/main/java/com/ze20/saifu/ui/log/logFragment.kt
  app/src/main/java/com/ze20/saifu/ui/wish/AddWishActivity.kt
  app/src/main/java/com/ze20/saifu/ui/wish/WishFragment.kt
  app/src/main/res/layout-land/activity_calendar.xml
  app/src/main/res/layout/activity_add_wish.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_data_input.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_report.xml
Labels: リファクタリング

#62 データ入力ボタンウィジェットの作成
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ze20/saifu/SaifuAddWidget.kt
  app/src/main/res/drawable-nodpi/addwidget_preview.png
  app/src/main/res/drawable/ic_launcher_round.png
  app/src/main/res/layout/saifu_add_widget.xml
  app/src/main/res/values-v14/dimens.xml
  app/src/main/res/values-v14/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/saifu_add_widget_info.xml
Labels: 機能強化

#63 readmeのバッジにリンクを設定
  README.md
Labels: ドキュメンテーション

#67 ショートカットを登録した後ホーム画面を再読込しないと表示されないバグを修正
  app/src/main/java/com/ze20/saifu/ui/home/HomeFragment.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment1.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment2.kt
  app/src/main/java/com/ze20/saifu/ui/home/sub_fragment3.kt
Labels: バグ

#66 ショートカットウィジェットの実装
  .editorconfig
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/ktlint.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ze20/saifu/Shortcut4Widget.kt
  app/src/main/res/drawable/shortcut_widget_preview.png
  app/src/main/res/layout-v26/shortcut4_widget.xml
  app/src/main/res/layout/saifu_add_widget.xml
  app/src/main/res/layout/shortcut4_widget.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/shortcut4_widget_info.xml
  build.gradle
Labels: 機能強化

#68 プロジェクト全体をktlintに従って修正
  app/src/main/java/com/ze20/saifu/SQLiteDB.kt
  app/src/main/java/com/ze20/saifu/ui/setting/SettingsActivity.kt
  build.gradle
Labels: リファクタリング
